### ISSUE TITLE
output the `MetadataBLOBPayload` to plain-text JSON file

### ISSUE THREAD

**Issue by equalsJeffH** [opotonniee/fido-mds-explorer#2]
It would be nice if there was a way to have the [`MetadataBLOBPayload`](https://fidoalliance.org/specs/mds/fido-metadata-service-v3.0-ps-20210518.html#metadata-blob-payload-dictionary) to be output to a (pretty-printed) plain-text JSON file.

and/or have a button that simply displays all the metadata entries in a single view, similar to the present view of an individual authenticator's metadata that one obtains by clicking on the authenticator name.

**Comment by opotonniee** [comment]
Hi Jeff
The whole purpose of this site was to present this blob is a nicer format than JSON :)
However the JSON is already logged in the browser javascript console, where it is displayed in foldable format. Is this sufficient for your need?

**Comment by equalsJeffH** [comment]
Hi Olivier,
> The whole purpose of this site was to present this blob is a nicer format than JSON :)

yes, it is very nice for humans to browse through.

though, it'd also be nice to be able to get a one-click decoded capture of the current `MetadataBLOBPayload`.

it is not a big deal, one ought to be able to cobble together some *nix command line tools that will also do it.

thanks in any case for providing this great tool!

**Comment by opotonniee** [comment]
Is the browser development tool output an acceptable workaround?
![image](https://user-images.githubusercontent.com/74671777/136810608-d0cd0d31-e35d-4c27-be70-22bfbe7b18c2.png)

**Comment by equalsJeffH** [comment]
> Is the browser development tool output an acceptable workaround?

sure. I was mostly just curious, thanks.

**Comment by opotonniee** [comment]
Hi Jeff
FYI, I updated my tool to decode the blob on the backend. The JSON can now be seen in https://github.com/opotonniee/fido-mds-explorer/blob/main/mds.js. The change history will thus be visible in git commits.
