### ISSUE TITLE
product listed

### ISSUE THREAD

**Issue by BernardJoly** [opotonniee/fido-mds-explorer#3]
hi
Onespan have some products certified since years, with mds explorer i cannot see these products.
could you please explain the problem?

**Comment by opoto** [comment]
Hello Bernard
This web site shows the full content of MDS v3 repository as published by FIDO Alliance (no filtering). Publication of authenticators to MDS is different from certification: MDS contains both certified and uncertificied products, and some certified products are not in MDS. To have your products listed in MDS you should contact your FIDO representative.

**Comment by BernardJoly** [comment]
thank you Olivier. i will check, why my device that i registered( i am FIDO representative) in Mds2 were not move in MDS3. i check with the new admin console of MDS3 and i found only one device registered.
