### ISSUE TITLE
Add column to show AAGUID/AAID/AttestationCertificateKeyIdentifiers

### ISSUE THREAD

**Issue by geofli** [opotonniee/fido-mds-explorer#8]
It is helpful to show AAGUID for FIDO2, AAID for UAF, AttestationCertificateKeyIdentifiers for U2F. This 3 can be one column since they would not exist at the same time for one metadata statement.
Then no need to jump into each metadata statement to find that.

**Comment by opotonniee** [comment]
Thanks for the suggestion, done in cec061a
